# Generated by Django 2.1.3 on 2019-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattachment',
            name='path',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='albums',
            unique_together={('album_name', 'user_profile')},
        ),
    ]
