# Generated by Django 2.1.3 on 2019-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0002_auto_20190426_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprofile',
            old_name='age',
            new_name='age_from',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='age_to',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
