# Generated by Django 2.1.3 on 2019-05-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0003_auto_20190428_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('can_see_wall', models.CharField(blank=True, max_length=50, null=True)),
                ('can_comment', models.CharField(blank=True, max_length=50, null=True)),
                ('can_contact_info', models.CharField(blank=True, max_length=50, null=True)),
                ('can_friends', models.CharField(blank=True, max_length=50, null=True)),
                ('can_send_message', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('response_all_time', models.BooleanField(default=False)),
                ('response_from', models.DateTimeField(null=True)),
                ('response_to', models.DateTimeField(null=True)),
                ('response_message', models.TextField(null=True)),
                ('auto_play_video', models.BooleanField(default=False)),
                ('jobs_notification', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(db_column='user_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to='casting_secret.UsersProfile')),
            ],
            options={
                'db_table': 'profile_settings',
                'managed': True,
            },
        ),
    ]
