# Generated by Django 2.1.3 on 2019-06-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0005_auto_20190515_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(db_column='user_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_viewers', to='casting_secret.UsersProfile')),
                ('visitor_profile', models.ForeignKey(db_column='visitor_profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='casting_secret.UsersProfile')),
            ],
            options={
                'db_table': 'profile_viewers',
                'managed': True,
            },
        ),
    ]
