# Generated by Django 2.1.3 on 2019-06-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0006_profileviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattachment',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
