# Generated by Django 2.1.3 on 2019-07-12 12:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityattachment',
            name='path_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
