# Generated by Django 2.1.3 on 2019-07-12 12:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0009_activityattachment_path_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattachment',
            name='path_json',
            field=jsonfield.fields.JSONField(default=dict, max_length=5000),
        ),
    ]
