# Generated by Django 2.1.3 on 2019-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0010_auto_20190712_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattachment',
            name='path_json',
            field=models.CharField(max_length=25),
        ),
    ]
