# Generated by Django 2.1.3 on 2019-08-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0012_auto_20190721_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='usersprofile',
            table=None,
        ),
    ]
