# Generated by Django 2.1.3 on 2019-08-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting_secret', '0013_auto_20190816_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'managed': True, 'verbose_name': 'Users profile'},
        ),
        migrations.AlterModelTable(
            name='usersprofile',
            table='users_profile',
        ),
    ]
